name: Deploy preview environment on Koyeb

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    needs: approval
    permissions:
      pull-requests: write
      actions: write
      deployments: write
    concurrency:
      group: '${{ github.head_ref }}'
      cancel-in-progress: true
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: '${{ secrets.KOYEB_API_TOKEN }}'

      - name: Login to Koyeb
        run: koyeb login --token '${{ secrets.KOYEB_API_TOKEN }}'
        
      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          git-branch: ${{ github.head_ref }}
          app-name: 'teambuilder'
          service-name: 'team-builder'
          service-ports: '4000:http'
          service-routes: '/:4000'
          service-instance-type: 'free'

permissions:
  pull-requests: write
